### ISSUE TITLE
[FIXED] Disable for .onion

### ISSUE THREAD

**Issue by sergeevabc** [balvin-perrie/http-to-https#2]
Dear @balvin-perrie,
I cannot access various *.onion websites, when your addon is switched on. Examples are [Flibusta][1] and [Scryptmail][2]. Perhaps, it’s the very time to introduce ignorelist feature or at least hardcode ignoring *.onion addresses as connections between user and internal Tor-based resources are already encrypted.

[1]: http://flibustahezeous3.onion/
[2]: http://scryptmaildniwm6.onion/

**Comment by balvin-perrie** [comment]
Thanks for the report. It is fixed. We will have an options page soon, for now it is a hard-coded bypass.

**Comment by sergeevabc** [comment]
It works as expected now, thank you.
